name: simple_validations
description: Some simple validations with messages for text field inputs.
version: 1.0.0
repository: https://github.com/godfreycomputing/simple_validations
environment:
  sdk: '>=2.15.1 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies: 
  intl: ^0.17.0
